### ISSUE TITLE
pinpoint web view problem

### ISSUE THREAD

**Issue by jiaojiaojiao** [peaksnail/pinpoint-node-agent#7]
in Pinpoint web requested page, "Argument" field is the collection which value?
The following example can be shown as "argument" field. and this is an HTTP request.

```
spanEventRecorder.recordServiceType(ServiceTypeConstants.http);
spanEventRecorder.recordAttribute(AnnotationConstants.http_url, con.serviceID);
```

but if it is a DUBBO request  , Which value should be "Argument" field
```
spanEventRecorder.recordServiceType(ServiceTypeConstants.node_zookeeper_dubbo);
```

**Comment by peaksnail** [comment]
You can define any value you want to record.
And It should be defined in java agent because it's written by java.

So, you should defined the filed in pinpoint agent ,for example DUBBO.header = 5000(for attention, don't be  duplicated with other plugin)
And then just execute  shell command "cd pinpoint/agent/utils/tools && node java_code_generator.js ${pluginName}". it will generate java plugin jar package of you node plugin.
finally ,put the jar package to the web and collector module

please refer to the details https://github.com/peaksnail/pinpoint-node-agent/wiki/Pinpoint-node-agent-Plugin-Developer-Guide and 
https://github.com/naver/pinpoint/wiki/Pinpoint-Plugin-Developer-Guide
